mkdir $home\code
mkdir $home\code\github
mkdir $home\code\github\jmbeach
mkdir $home\code\bitbucket
mkdir $home\code\bitbucket\jmbeach
mkdir $home\code\sandbox
mkdir $home\bin
mkdir $home\bin\shims
mkdir .\logs